### ISSUE TITLE
Phone stuck in TWRP recovery.

### ISSUE THREAD

**Issue by JalalKhanSL** [lopestom/twrp_device_tecno_CH6i#1]
Hello.
I compiled twrp`s sources with this Device tree for Tecno camon 19 NEO CH6i, the twrp recovery installed successfully but my phone always boot in twrp recovery instead Android os.
I`m stuck here.

**Comment by lopestom** [comment]
> Hello. I compiled twrp`s sources with this Device tree for Tecno camon 19 NEO CH6i, the twrp recovery installed successfully but my phone always boot in twrp recovery instead Android os. I`m stuck here.

Did you use DT without modifying anything for the version of Android that is on your device?

[4pda link1](https://4pda.to/forum/index.php?showtopic=1044228&view=findpost&p=132224107)
[4pda link2](https://4pda.to/forum/index.php?showtopic=1044228&view=findpost&p=122352438)

**Comment by JalalKhanSL** [comment]
Yes, I used the DT without modifying it, is there anything i need to change before compiling.

**Comment by lopestom** [comment]
> Yes, I used the DT without modifying it, is there anything i need to change before compiling.

But of course you can!

Put files and information from the same firmware version that is on your device.

Just don't ask me how! Do it yourself.
https://gist.github.com/lopestom/c4a2648958db5c3db03d32033a3583cd

**Comment by JalalKhanSL** [comment]
ok, I`ll follow instruction on this  (https://gist.github.com/lopestom/c4a2648958db5c3db03d32033a3583cd) , I`ll also try this given [(Device Tree)](https://github.com/infinixs5lite/android_device_CH6i-TWRP.git)
I hope it`ll work.

**Comment by lopestom** [comment]
> ok, I`ll follow instruction on this (https://gist.github.com/lopestom/c4a2648958db5c3db03d32033a3583cd) , I`ll also try this given [(Device Tree)](https://github.com/infinixs5lite/android_device_CH6i-TWRP.git) I hope it`ll work.

220922V1236
